# Generated by Django 4.2 on 2023-04-19 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompaniesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("industry", models.CharField(max_length=255)),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=10)),
                ("employees", models.IntegerField()),
                ("country", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Normalize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The normalized name.", max_length=255, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyNormalize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalizations",
                        to="api.companiesdata",
                    ),
                ),
                (
                    "normalized_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.normalize"
                    ),
                ),
            ],
            options={
                "unique_together": {("normalized_name", "company")},
            },
        ),
    ]
