# Generated by Django 4.2 on 2023-04-19 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="companiesdata",
            table="companies_data",
        ),
        migrations.AlterModelTable(
            name="companynormalize",
            table="company_normalize",
        ),
        migrations.AlterModelTable(
            name="normalize",
            table="normalize",
        ),
    ]
